let
  inherit (builtins) isBool isString isInt;
  types = {
    "vim.opt.list" = isBool;
    "vim.opt.shell" = isString;
    "vim.opt.shadafile" = isString;
    "vim.opt.termguicolors" = isBool;
    "vim.opt.undofile" = isBool;
    "vim.opt.tabstop" = isInt;
    "vim.opt.shiftwidth" = isInt;
    "vim.opt.shiftround" = isBool;
    "vim.opt.expandtab" = isBool;
    "vim.opt.scrolloff" = isInt;
    "vim.opt.mouse" = isString;
    "vim.opt.cursorline" = isBool;
    "vim.opt.relativenumber" = isBool;
    "vim.opt.number" = isBool;
    "vim.opt.viminfo" = isString;
    "vim.opt.viminfofile" = isString;
    "vim.opt.ignorecase" = isBool;
    "vim.opt.ttimeoutlen" = isInt;
    "vim.opt.compatible" = isBool;
    "vim.opt.shortmess" = isString;
    "vim.opt.wrap" = isBool;
    "vim.opt.linebreak" = isBool;
    "vim.opt.errorbells" = isBool;
    "vim.opt.swapfile" = isBool;
    "vim.opt.showmode" = isBool;
    "vim.opt.autoindent" = isBool;
    "vim.opt.autoread" = isBool;
    "vim.opt.backup" = isBool;
    "vim.opt.clipboard" = isString;
    "vim.opt.cmdheight" = isInt;
    "vim.opt.completeopt" = isString;
    "vim.opt.fileencoding" = isString;
    "vim.opt.fileformat" = isString;
    "vim.opt.hidden" = isBool;
    "vim.opt.incsearch" = isBool;
    "vim.opt.laststatus" = isInt;
    "vim.opt.smartcase" = isBool;
    "vim.opt.smartindent" = isBool;
    "vim.opt.spelllang" = isString;
    "vim.opt.splitbelow" = isBool;
    "vim.opt.splitright" = isBool;
    "vim.opt.timeoutlen" = isInt;
    "vim.opt.writebackup" = isBool;
  };
in types
